# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Coastal Coding
email: pfuzane@coastalcoding.com
description: > # this means to ignore newlines until "baseurl:"
  We inspire and motivate students to go beyond their expectations for what they can do in Software Development and their careers. We do this through top quality software development educators who teach current and modern material and give 1:1 coaching with students on career opportunities. Our students experience life change through this program and are prepared for any opportunity in Software Development when they graduate.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://coastalcoding.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

gems: ['kramdown']
exclude: ['config.ru', 'Gemfile', 'Gemfile.lock', 'vendor', 'Procfile', 'Rakefile']

